Repository doctrine/DoctrineFixturesBundle, pull requests merged in 2023-11, with the labels that each got.

#411 Drop support for DBAL 2
  Command/LoadDataFixturesDoctrineCommand.php
  composer.json
  phpstan-baseline.neon
Labels: Improvement

#409 Add native return types everywhere
  Command/CommandCompatibility.php
  Command/LoadDataFixturesDoctrineCommand.php
  DependencyInjection/DoctrineFixturesExtension.php
  DoctrineFixturesBundle.php
  Purger/ORMPurgerFactory.php
  Tests/IntegrationTest.php
  phpcs.xml.dist
  psalm.xml
Labels: Improvement

#410 Apply PHPCS' PHP 7.4 rules
  Command/LoadDataFixturesDoctrineCommand.php
  Loader/SymfonyFixturesLoader.php
  Tests/Command/LoadDataFixturesDoctrineCommandTest.php
  phpcs.xml.dist
Labels: Improvement

#412 Apply PHPCS' PHP 8.1 rules
  Command/LoadDataFixturesDoctrineCommand.php
  Loader/SymfonyFixturesLoader.php
  Purger/ORMPurgerFactory.php
  Purger/PurgerFactory.php
  Tests/IntegrationTest.php
  Tests/IntegrationTestKernel.php
  phpcs.xml.dist
Labels: Improvement

#413 Prepare 3.5.0
  .symfony.bundle.yaml
Labels: Documentation

#416 Upgrade to Psalm 5
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: CI

#415 Add support for doctrine/orm 3
  Tests/IntegrationTest.php
  composer.json
  psalm.xml
Labels: Improvement
