Repository doctrine/DoctrineFixturesBundle, pull requests merged in 2023-10, with the labels that each got.

#402 Support Symfony 7
  Command/CommandCompatibility.php
  Command/LoadDataFixturesDoctrineCommand.php
  Loader/SymfonyBridgeLoader.php
  Loader/SymfonyFixturesLoader.php
  Tests/IntegrationTest.php
  Tests/IntegrationTestKernel.php
  composer.json
  phpcs.xml.dist
  psalm.xml
Labels: Improvement

#405 CI: Bump workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  psalm.xml
Labels: CI

#404 Doctrine CS 12
  Command/LoadDataFixturesDoctrineCommand.php
  DependencyInjection/DoctrineFixturesExtension.php
  Purger/PurgerFactory.php
  Tests/Command/LoadDataFixturesDoctrineCommandTest.php
  Tests/IntegrationTest.php
  composer.json
Labels: Improvement

#393 Add documentation for yaml service configuration
  Resources/doc/index.rst
Labels: Documentation

#403 Drop support for Symfony 3 + 4
  .github/workflows/continuous-integration.yml
  Command/LoadDataFixturesDoctrineCommand.php
  Loader/SymfonyFixturesLoader.php
  Tests/Command/LoadDataFixturesDoctrineCommandTest.php
  Tests/IntegrationTestKernel.php
  Tests/Purger/ORMPurgerFactoryTest.php
  composer.json
Labels: Improvement
